#!/bin/bash

function util_powerLS {
    if [ "$2" == "" ]; then
	ls -1

    else
	for i in `ls -1 | sort`; do
	    if [ "" != "$4" ]; then
		if [ "$i" "$1" "$2" -a "$i" "$3" "$4" ]; then
		    echo $i
		fi

	    elif [ "" != "$2" ]; then
		if [ "$i" "$1" "$2" ]; then
		    echo $i;
		fi
		
	    fi;
	done
    fi
}